name: GitHub Metrics

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate top metrics
        uses: lowlighter/metrics@latest
        with:
          filename: top.svg
          token: ${{ secrets.METRICS }}
          
          # Using your PAT for the commit itself
          committer_token: ${{ secrets.METRICS }}
          committer_name: ${{ secrets.GIT_NAME }}
          committer_email: ${{ secrets.GIT_EMAIL }}
          
          # This forces a unique commit hash every time
          committer_message: "feat: update metrics - $(date +'%Y-%m-%d') [skip ci]"

          user: Chintanpatel24
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          
          # This forces the API to get new data, not cached data
          use_precomputed_data: no

          plugin_achievements: yes
          plugin_languages: yes
          plugin_lines: yes

      - name: Generate bottom metrics
        uses: lowlighter/metrics@latest
        with:
          filename: bottom.svg
          token: ${{ secrets.METRICS }}
          committer_token: ${{ secrets.METRICS }}
          committer_name: ${{ secrets.GIT_NAME }}
          committer_email: ${{ secrets.GIT_EMAIL }}
          committer_message: "feat: update metrics bottom [skip ci]"

          user: Chintanpatel24
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
